version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  assignees:
  - shamil
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.20
